force-app/main/default/objects/WorkOrder/fields/Report_Generation_Flag__c.field-meta.xml
<CustomField>
    <fullName>Report_Generation_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Report Generation Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Service_Report_Signature__c.field-meta.xml
<CustomField>
    <fullName>Service_Report_Signature__c</fullName>
    <label>Service Report Signature</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/serviceReportController.cls
public without sharing class serviceReportController {
    @AuraEnabled
    public static void updateWO(String recordId, String signatureBase64){
        WorkOrder wo = [SELECT Report_Generation_Flag__c, Service_Report_Signature__c FROM WorkOrder WHERE Id =: recordId LIMIT 1];
        if(wo.Report_Generation_Flag__c == true){
            wo.Report_Generation_Flag__c = false;
        }else{
            wo.Report_Generation_Flag__c = true;
        }
        if(signatureBase64 != ''){
            wo.Service_Report_Signature__c = signatureBase64;
        }
        update wo;
    }
}